### ISSUE TITLE
Bypass BanSystem

### ISSUE THREAD

**Issue by xxAROX** [StimoMC/Docs#1]
I got the information, that players can bypass the ban.
Just set banned players immobile or something like that..

**Comment by xxFLORII** [comment]
fixed

**Comment by xxAROX** [comment]
lmao

**Comment by xxAROX** [comment]
got notification
![grafik](https://user-images.githubusercontent.com/57589973/193062636-c85f1e26-d8a7-4ae9-8b9a-1b62de7c951c.png)
